/**
 * 
 */
package com.vsign.tech.rest.constant;

/**
 * @author Hemraj
 *
 */
public enum ProductCodes {
	
	HARD_BINDING,
	SPIRAL_BINDING,	
	COLLEGE_PROJECTS,
	HS_PRISCRIPTION_PAD,
	HS_BUSINESS_CARD,
	HS_FOLDER_FILE,
	HS_PAMPHLET,
	HS_REFERRAL_PAD,
	HS_ENVELOP,
	HS_BROUCHER,
	HS_OPD_REGISTER,
	CUSTOM_T_SHIRT,
	CUSTOM_BAG,
	CUSTOM_CUP,
	MKTNG_POSTER,	
	MKTNG_MULYI_CLR_PAMPHLET,
	MKTNG_LEAF_LET,
	MKTNG_BROUCHER,
	MKTNG_GLOW_SHINE_BOARD,
	OFFICE_LETTER_HEAD,
	OFFICE_BUSINESS_CARD,
	OFFICE_BROUCHER,
	OFFICE_ENVELOP,	
	OFFICE_RECEIPT_BOOK,
	OFFICE_FOLDER,
	OFFICE_I_CARD,
	OFFICE_MULTI_COLOR_FILE
	
}
